#' plot total within cluster variations
#'
#' @import ggplot2
#' @param clusters a list of cluster objects generated by make_cluster
#' @return a ggplot of total within cluster variation
#' @export
#'
#' @examples
#' library(ggplot2)
#'
#' data = data.frame(1:4, c(3,6,8,2), c(4,8,10,2))
#' set.seed(1)
#' n_clusters = 3
#' clusters = list()
#' for (i in 1:n_clusters) {
#'    clusters[[i]] = make_cluster(data, kmeans, centers = i, nstart = 5, iter.max = 10)}
#' set.seed(NULL)
#'
#' tot_within_var_plot(clusters = clusters) +
#' scale_x_continuous(n.breaks = n_clusters)
tot_within_var_plot = function(clusters) {
  toplot = matrix(nrow = 0, ncol = 2, dimnames = list(c(),c('cluster_number','tot_within_var')))
  for (clus in clusters) {
    toplot = rbind(toplot, c(length(clus$size), clus$tot.withinss))
  }
  toplot = as.data.frame(toplot)
  p = ggplot(toplot, aes(x=cluster_number, y = tot_within_var)) +
    geom_line(colour = 'black') +
    geom_point(colour = 'royalblue4') +
    labs(x='number of clusters',y='total variation within clusters') +
    ggpubr::theme_pubr()
  return(p)
}
